services:
  - type: web
    name: n8n
    env: docker
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: kodhax
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Xpto512004#
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_TUNNEL_URL
        value: https://kodhax.n8n.onrender.com
